title: Samson Imoleayo Kolawole
logo: Kolaay.jpg
description: >
  A results-driven data analyst with over five years of experience leveraging Microsoft Excel, SQL, and Power BI to deliver actionable insights and support data-driven decision-making.
  Skilled in Excel for advanced data automation, including pivot tables, Power Query, and VBA. Proficient in SQL for data extraction, transformation, and analysis of complex datasets.
  
theme: jekyll-theme-minimal

