tittle: Samson Imoleayo Kolawole

logo: IMG_20200328_223215_449 (1).jpg

description: Results-driven Data Analyst with over five years of experience leveraging Microsoft Excel, SQL, and Power BI.
  Proficient in SQL for data extraction, transformation, and analysis of complex datasets.
  Skilled in Power BI for building interactive dashboards and business intelligence reports.
  Strong experience in Excel automation, data cleaning, and ETL processes.

#google_analytics:

theme: jekyll_theme_minimal
