title: Samson Imoleayo Kolawole
logo: [SamsonPasportp(1)](SamsonPasportp(1).jpg)
description: >
  Results-driven Data Analyst with 5+ years of experience in Excel, SQL, and Power BI.
  Skilled in data analysis, automation, and dashboard development.
theme: jekyll-theme-minimal
